In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

**데이터셋 불러오기**

In [ ]:
import pandas as pd

승하차인원 = pd.read_csv('/content/drive/MyDrive/서울시 빅데이터 공모전/data/raw/서울시 지하철 호선별 역별 시간대별 승하차 인원 현황.csv', encoding='utf-8')

/tmp/ipykernel_1691/3068449997.py:3: DtypeWarning: Columns (0,1,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52) have mixed types. Specify dtype option on import or set low_memory=False.
  승하차인원 = pd.read_csv('/content/drive/MyDrive/서울시 빅데이터 공모전/data/raw/서울시 지하철 호선별 역별 시간대별 승하차 인원 현황.csv', encoding='utf-8')

In [ ]:
승하차인원.head()
승하차인원.columns
승하차인원.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80488 entries, 0 to 80487
Data columns (total 53 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   순번            80488 non-null  object
 1   사용월           80488 non-null  object
 2   호선명           80488 non-null  object
 3   지하철역          80488 non-null  object
 4   04시-05시 승차인원  80488 non-null  object
 5   04시-05시 하차인원  80488 non-null  object
 6   05시-06시 승차인원  80488 non-null  object
 7   05시-06시 하차인원  80488 non-null  object
 8   06시-07시 승차인원  80488 non-null  object
 9   06시-07시 하차인원  80488 non-null  object
 10  07시-08시 승차인원  80488 non-null  object
 11  07시-08시 하차인원  80488 non-null  object
 12  08시-09시 승차인원  80488 non-null  object
 13  08시-09시 하차인원  80488 non-null  object
 14  09시-10시 승차인원  80488 non-null  object
 15  09시-10시 하차인원  80488 non-null  object
 16  10시-11시 승차인원  80488 non-null  object
 17  10시-11시 하차인원  80488 non-null  object
 18  11시-12시 승차인원  80488 non-null  object
 19  11시-12시 하차인원  80488 non-null  object
 20  12시-13시 승차인원  80488 non-null  object
 21  12시-13시 하차인원  80488 non-null  object
 22  13시-14시 승차인원  80488 non-null  object
 23  13시-14시 하차인원  80488 non-null  object
 24  14시-15시 승차인원  80488 non-null  object
 25  14시-15시 하차인원  80488 non-null  object
 26  15시-16시 승차인원  80488 non-null  object
 27  15시-16시 하차인원  80488 non-null  object
 28  16시-17시 승차인원  80488 non-null  object
 29  16시-17시 하차인원  80488 non-null  object
 30  17시-18시 승차인원  80488 non-null  object
 31  17시-18시 하차인원  80488 non-null  object
 32  18시-19시 승차인원  80488 non-null  object
 33  18시-19시 하차인원  80488 non-null  object
 34  19시-20시 승차인원  80488 non-null  object
 35  19시-20시 하차인원  80488 non-null  object
 36  20시-21시 승차인원  80488 non-null  object
 37  20시-21시 하차인원  80488 non-null  object
 38  21시-22시 승차인원  80488 non-null  object
 39  21시-22시 하차인원  80488 non-null  object
 40  22시-23시 승차인원  80488 non-null  object
 41  22시-23시 하차인원  80488 non-null  object
 42  23시-24시 승차인원  80488 non-null  object
 43  23시-24시 하차인원  80488 non-null  object
 44  00시-01시 승차인원  80488 non-null  object
 45  00시-01시 하차인원  80488 non-null  object
 46  01시-02시 승차인원  80488 non-null  object
 47  01시-02시 하차인원  80488 non-null  object
 48  02시-03시 승차인원  80488 non-null  object
 49  02시-03시 하차인원  80488 non-null  object
 50  03시-04시 승차인원  80488 non-null  object
 51  03시-04시 하차인원  80488 non-null  object
 52  작업일자          80488 non-null  object
dtypes: object(53)
memory usage: 32.5+ MB

In [ ]:
import pandas as pd

B078 = pd.read_csv('/content/drive/MyDrive/서울시 빅데이터 공모전/data/캠퍼스 반출/반출데이터300.csv', encoding='euc-kr')

In [ ]:
B078.head()
B078.columns
B078.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1232 entries, 0 to 1231
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   station_name    1232 non-null   object
 1   time_group      1232 non-null   object
 2   line_name       1232 non-null   object
 3   total_pop_sum   1232 non-null   float64
 4   child_pop_sum   1232 non-null   float64
 5   youth_pop_sum   1232 non-null   float64
 6   middle_pop_sum  1232 non-null   float64
 7   elder_pop_sum   1232 non-null   float64
dtypes: float64(5), object(3)
memory usage: 77.1+ KB

In [ ]:
import pandas as pd

이격거리 = pd.read_csv('/content/drive/MyDrive/서울시 빅데이터 공모전/data/raw/이격거리통합.csv', encoding='euc-kr')

In [ ]:
이격거리.head()
이격거리.columns
이격거리.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21088 entries, 0 to 21087
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   철도운영기관명  21088 non-null  object
 1   선명       21088 non-null  object
 2   역명       21088 non-null  object
 3   승강장번호    21088 non-null  int64
 4   차량순서     21088 non-null  int64
 5   차량출입문번호  21088 non-null  int64
 6   안전거리     21064 non-null  float64
dtypes: float64(1), int64(3), object(3)
memory usage: 1.1+ MB

In [ ]:
import pandas as pd

환승역 = pd.read_csv(
    '/content/drive/MyDrive/서울시 빅데이터 공모전/data/raw/서울교통공사_환승역환승인원정보_20251130.csv',
    encoding='cp949'
)

In [ ]:
환승역.head()
환승역.columns
환승역.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73 entries, 0 to 72
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   연번       73 non-null     int64
 1   역명       73 non-null     object
 2   평일(일평균)  73 non-null     int64
 3   토요일      73 non-null     int64
 4   일요일      73 non-null     int64
dtypes: int64(4), object(1)
memory usage: 3.0+ KB

In [ ]:
import pandas as pd

사고 = pd.read_csv('/content/drive/MyDrive/서울시 빅데이터 공모전/data/raw/서울교통공사_최근 5년 지하철 사고 현황_20250630.csv', encoding='euc-kr')

In [ ]:
사고.head()
사고.columns
사고.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2404 entries, 0 to 2403
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   연번      2404 non-null   int64
 1   발생일     2404 non-null   object
 2   사고유형    2404 non-null   object
 3   발생역     2398 non-null   object
 4   발생시간    2404 non-null   object
 5   비고      0 non-null      float64
dtypes: float64(1), int64(1), object(4)
memory usage: 112.8+ KB

데이터 정리
* **승하차 인원, B078, 이격거리, 환승역, 사고**

승하차 인원 데이터셋 전처리 : 서울지하철 1~9호선만 남기고 시간대 그룹 만들었음(b078과 동일하게)

In [ ]:
# 1) 호선명에서 1호선~9호선만 남기기
승하차인원 = 승하차인원[승하차인원['호선명'].astype(str).str.contains(r'^[1-9]호선$', na=False)].copy()

# 확인
승하차인원['호선명'].unique()

array(['2호선', '3호선', '6호선', '4호선', '1호선', '9호선', '5호선', '7호선', '8호선'],
      dtype=object)

In [ ]:
print(승하차인원.columns.tolist())

['순번', '사용월', '호선명', '지하철역', '04시-05시 승차인원', '04시-05시 하차인원', '05시-06시 승차인원', '05시-06시 하차인원', '06시-07시 승차인원', '06시-07시 하차인원', '07시-08시 승차인원', '07시-08시 하차인원', '08시-09시 승차인원', '08시-09시 하차인원', '09시-10시 승차인원', '09시-10시 하차인원', '10시-11시 승차인원', '10시-11시 하차인원', '11시-12시 승차인원', '11시-12시 하차인원', '12시-13시 승차인원', '12시-13시 하차인원', '13시-14시 승차인원', '13시-14시 하차인원', '14시-15시 승차인원', '14시-15시 하차인원', '15시-16시 승차인원', '15시-16시 하차인원', '16시-17시 승차인원', '16시-17시 하차인원', '17시-18시 승차인원', '17시-18시 하차인원', '18시-19시 승차인원', '18시-19시 하차인원', '19시-20시 승차인원', '19시-20시 하차인원', '20시-21시 승차인원', '20시-21시 하차인원', '21시-22시 승차인원', '21시-22시 하차인원', '22시-23시 승차인원', '22시-23시 하차인원', '23시-24시 승차인원', '23시-24시 하차인원', '00시-01시 승차인원', '00시-01시 하차인원', '01시-02시 승차인원', '01시-02시 하차인원', '02시-03시 승차인원', '02시-03시 하차인원', '03시-04시 승차인원', '03시-04시 하차인원', '작업일자']

In [ ]:
for i, col in enumerate(승하차인원.columns):
    print(i, repr(col))

0 '순번'
1 '사용월'
2 '호선명'
3 '지하철역'
4 '04시-05시 승차인원'
5 '04시-05시 하차인원'
6 '05시-06시 승차인원'
7 '05시-06시 하차인원'
8 '06시-07시 승차인원'
9 '06시-07시 하차인원'
10 '07시-08시 승차인원'
11 '07시-08시 하차인원'
12 '08시-09시 승차인원'
13 '08시-09시 하차인원'
14 '09시-10시 승차인원'
15 '09시-10시 하차인원'
16 '10시-11시 승차인원'
17 '10시-11시 하차인원'
18 '11시-12시 승차인원'
19 '11시-12시 하차인원'
20 '12시-13시 승차인원'
21 '12시-13시 하차인원'
22 '13시-14시 승차인원'
23 '13시-14시 하차인원'
24 '14시-15시 승차인원'
25 '14시-15시 하차인원'
26 '15시-16시 승차인원'
27 '15시-16시 하차인원'
28 '16시-17시 승차인원'
29 '16시-17시 하차인원'
30 '17시-18시 승차인원'
31 '17시-18시 하차인원'
32 '18시-19시 승차인원'
33 '18시-19시 하차인원'
34 '19시-20시 승차인원'
35 '19시-20시 하차인원'
36 '20시-21시 승차인원'
37 '20시-21시 하차인원'
38 '21시-22시 승차인원'
39 '21시-22시 하차인원'
40 '22시-23시 승차인원'
41 '22시-23시 하차인원'
42 '23시-24시 승차인원'
43 '23시-24시 하차인원'
44 '00시-01시 승차인원'
45 '00시-01시 하차인원'
46 '01시-02시 승차인원'
47 '01시-02시 하차인원'
48 '02시-03시 승차인원'
49 '02시-03시 하차인원'
50 '03시-04시 승차인원'
51 '03시-04시 하차인원'
52 '작업일자'

In [ ]:
df = 승하차인원.copy()

# 혹시 공백 제거
df.columns = df.columns.str.strip()

# 시간대 컬럼 (승차인원, 하차인원)
time_cols = [col for col in df.columns if ('승차인원' in col) or ('하차인원' in col)]

print(len(time_cols))
print(time_cols[:5])

48
['04시-05시 승차인원', '04시-05시 하차인원', '05시-06시 승차인원', '05시-06시 하차인원', '06시-07시 승차인원']

In [ ]:
long_df = df.melt(
    id_vars=['사용월', '호선명', '지하철역'],
    value_vars=time_cols,
    var_name='time_type',
    value_name='count'
)

In [ ]:
# 컬럼이 숫자가 아니라 문자열처럼 이어붙은 값을 깨진거 처리하기
long_df['count'] = (
    long_df['count']
    .astype(str)
    .str.replace(',', '', regex=False)
)

long_df['count'] = pd.to_numeric(long_df['count'], errors='coerce').fillna(0)

In [ ]:
long_df['hour'] = long_df['time_type'].str.extract(r'(\d{2})시').astype(int)

In [ ]:
def make_time_group(hour):
    if 7 <= hour < 9:
        return '출근시간'
    elif 9 <= hour < 16:
        return '낮시간'
    elif 16 <= hour < 20 :
        return '퇴근시간'
    else:
        return '기타'

long_df['time_group'] = long_df['hour'].apply(make_time_group)

In [ ]:
승하차인원_전처리 = (
    long_df
    .groupby(['사용월', '호선명', '지하철역', 'time_group'], as_index=False)
    .agg(혼잡=('count', 'sum'))
)

In [ ]:
승하차인원_전처리.head()

      사용월  호선명 지하철역 time_group      혼잡
0  201502  1호선  동대문         기타  169074
1  201502  1호선  동대문        낮시간  439588
2  201502  1호선  동대문       출근시간   75265
3  201502  1호선  동대문       퇴근시간  253230
4  201502  1호선  동묘앞         기타   53548

In [ ]:
# 변수로 저장
승하차인원 = 승하차인원_전처리.copy()

# 파일로 저장
승하차인원.to_csv(
    '/content/drive/MyDrive/승하차인원_전처리.csv',
    index=False,
    encoding='cp949'
)

In [ ]:
승하차인원.head(10)

      사용월  호선명 지하철역 time_group       혼잡
0  201502  1호선  동대문         기타   169074
1  201502  1호선  동대문        낮시간   439588
2  201502  1호선  동대문       출근시간    75265
3  201502  1호선  동대문       퇴근시간   253230
4  201502  1호선  동묘앞         기타    53548
5  201502  1호선  동묘앞        낮시간   290395
6  201502  1호선  동묘앞       출근시간    40867
7  201502  1호선  동묘앞       퇴근시간   158787
8  201502  1호선  서울역         기타   668606
9  201502  1호선  서울역        낮시간  1424527

이격거리 데이터셋 전처리 : 각 역 별 이격거리의 평균, 최소, 최대만 뽑아냄

In [ ]:
이격거리= (
    이격거리
    .groupby(['선명', '역명'], as_index=False)
    .agg(
        구조평균=('안전거리', 'mean'),
        구조최소=('안전거리', 'min'),
        구조최대=('안전거리', 'max')
    )
)

In [ ]:
이격거리.head(20)

     선명            역명      구조평균  구조최소  구조최대
0   1호선           동대문  12.66250  10.0  19.0
1   1호선           동묘앞   6.83750   3.0  12.0
2   1호선           서울역  10.82125   1.5  21.0
3   1호선            시청   9.23750   2.0  15.0
4   1호선           신설동  12.26250   7.0  20.0
5   1호선           제기동  10.45000   3.0  17.0
6   1호선            종각   8.85000   7.0  11.0
7   1호선          종로3가   9.38250   2.0  17.0
8   1호선          종로5가   9.42500   8.0  11.0
9   1호선  청량리(서울시립대입구)   8.60000   4.0  18.0
10  2호선            강남   8.04500   6.5   9.5
11  2호선    강변(동서울터미널)   6.95000   4.0  10.0
12  2호선          건대입구   9.04125   7.0  10.5
13  2호선    교대(법원·검찰청)   8.53750   6.3   9.6
14  2호선       구로디지털단지   9.10000   2.5  14.5
15  2호선      구의(광진구청)   8.21250   7.0   9.5
16  2호선           까치산   8.18750   7.0   9.5
17  2호선           낙성대   8.63125   6.5   9.0
18  2호선            당산   8.65625   5.5  12.0
19  2호선      대림(구로구청)   8.23750   5.0   9.0

환승역 데이터셋 전처리 : 따로 하지 않음. 그대로 사용 추후에 평균 낼 것.

In [ ]:
환승역.head(10)

   연번         역명  평일(일평균)     토요일     일요일
0   1        신도림   269275  229757  165107
1   2  동대문역사문화공원   226341  193636  144058
2   3      고속터미널   186833  161327  116415
3   4        왕십리   177260  138662   98515
4   5        서울역   163998  156550  117615
5   6         사당   160880  138295   97565
6   7       종로3가   153242  147402  101038
7   8        충무로   141817  122893   86220
8   9         교대   138032   98593   65561
9  10         잠실   122968   82219   58534

사고 데이터셋 전처리 : 역별, 시간대별로 사고 수 집계함. 다른 데이터셋과의 merge위해 역명과 호선 통일함

In [ ]:
사고['hour'] = 사고['발생시간'].str.split(':').str[0].astype(int)

def make_time_group(hour):
    if 7 <= hour < 9:
        return '출근시간'
    elif 9 <= hour < 16:
        return '낮시간'
    elif 16 <= hour < 20:
        return '퇴근시간'
    else:
        return '기타'

사고['time_group'] = 사고['hour'].apply(make_time_group)

In [ ]:
# 날짜 처리
사고['발생일'] = pd.to_datetime(사고['발생일'], errors='coerce')

사고['사용월'] = 사고['발생일'].dt.strftime('%Y%m').astype(int)

# 역명 정리 함수 정의
import re

def clean_station_name(x):
    if pd.isna(x):
        return x

    x = str(x)
    x = re.sub(r'\(\d+\)', '', x)  # 교대(2)역 -> 교대역
    x = x.replace('역', '')        # 교대역 -> 교대
    x = x.strip()

    return x

In [ ]:
import numpy as np
사고['역명_clean'] = 사고['발생역'].apply(clean_station_name)

# 호선 추출 (예: 교대(2)역 → 2호선)
사고['호선명'] = 사고['발생역'].str.extract(r'\((\d+)\)').astype(float).astype('Int64').astype(str) + '호선'

# 없는 경우 처리
사고['호선명'] = 사고['호선명'].replace('<NA>호선', np.nan)

In [ ]:
사고= (
    사고
    .groupby(['사용월', '역명_clean', '호선명', 'time_group'], as_index=False)
    .size()
    .rename(columns={'size': '사고수'})
)

In [ ]:
사고.tail(100)

        사용월 역명_clean  호선명 time_group  사고수
826  202412       잠실  8호선       퇴근시간    2
827  202412     종로3가  3호선       퇴근시간    1
828  202412       합정  6호선       출근시간    1
829  202501     건대입구  7호선         기타    1
830  202501    고속터미널  3호선       퇴근시간    1
..      ...      ...  ...        ...  ...
921  202506       공덕  5호선       출근시간    1
922  202506       교대  2호선        낮시간    1
923  202506       사당  2호선       퇴근시간    1
924  202506      신설동  1호선        낮시간    1
925  202506      충무로  4호선        낮시간    1

[100 rows x 5 columns]

# 서연 추가

## 민영이랑 고민해볼 것
### 시간대 그룹이 너무 거칠 수 있음
- 지금 출근시간/낮시간/퇴근시간/기타로 되어있는데
- 보고서용으로는 이게 좋긴한데 더 정교하게 하려면 hour 단위로 하는게 좋다네?
- 왜냐하면 퇴근시간=16 ~ 19시인데 실제 위험은 18시가 가장 클 수 있는데 16 ~ 19시를 다 합치면 18시 피크가 흐려질 수 있어서
- 추천은 1차분석: time_group 사용하고 2차분석: hour단위 사용
- 나중에 시간대별 동적 위험도를 강조하려면 hour 단위 분석도 추가하면 좋을듯
- 일단은 지금처럼 ㄱㄱ!

### 이격거리 변수는 평균보다 최대값 중심이 좋다는 거 기억하기
- 현재 구조평균, 최소, 최대 만들어놨는데 최종 위험도에는 구조최대를 사용하기
- 이유: 승강장 사고는 전체 평균보다 가장 위험한 구간의 이격거리가 더 직접적인 위험 요인이 될 수 있기 때문

### 환승역 데이터는 환승 여부만 쓰면 약함? -> 지금은 환승이면 1, 아니면 0으로만 처리
- 이것도 괜찮긴 한데 가능하면 환승인원까지 쓰는게 더 좋대
- 이유: 환승역이라고 다 같은 환승역이 아니니까
- 예를들어 신도림, 고속터미널, 사당같은 곳은 환승 압력이 훨씬 크고 작은 환승역은 영향이 적을 수 있음
- 그래서 나중에 가능하면 환승여부 + 환승인원 둘 다 쓰는게 설득력 있을듯!
- 시간이 부족하면 일단 환승여부만 쓰기

### 이격거리 데이터에 9호선이 아에 없음 !!!
- 현재 이격거리 데이터 범위가 1호선 ~ 8호선
- gpt의 추천: 구조위험 있는 역만 우선 분석
```
df_final_struct = df_final.dropna(subset=['구조최대']).copy()

print(df_final_struct.shape)
print(df_final_struct['구조최대'].isna().sum())
```
- 보고서에는: 승강장 이격거리 데이터는 1~8호선 일부 역을 대상으로 제공되어,
구조위험을 포함한 최종 위험도 분석은 이격거리 정보가 존재하는 역을 중심으로 수행하였다.
9호선 및 일부 외부 운영 구간은 구조위험 미보유 구간으로 분리하였다. 이런식으로 작성?

In [ ]:
# 역명 통일 부족한 것 역명 통일시키기
import re

def clean_station_name(x):
    x = str(x).strip()
    x = x.replace(' ', '')
    x = x.replace('（', '(').replace('）', ')')
    x = re.sub(r'\(.*?\)', '', x)
    x = x.replace('역', '')
    return x

승하차인원['역명_clean'] = 승하차인원['지하철역'].apply(clean_station_name)
이격거리['역명_clean'] = 이격거리['역명'].apply(clean_station_name)
환승역['역명_clean'] = 환승역['역명'].apply(clean_station_name)
사고['역명_clean'] = 사고['역명_clean'].apply(clean_station_name)

# 동대문역사문화공원 -> 동대문사문화공원 으로 생성되는 오류 발생

In [ ]:
import re

def clean_station_name(x):
    x = str(x).strip()
    x = x.replace(' ', '')
    x = x.replace('（', '(').replace('）', ')')

    # 괄호 안 내용 제거: 교대(2)역 -> 교대역
    x = re.sub(r'\(.*?\)', '', x)

    # 문자열 맨 끝의 '역'만 제거
    x = re.sub(r'역$', '', x)

    return x

In [ ]:
승하차인원['역명_clean'] = 승하차인원['지하철역'].apply(clean_station_name)
이격거리['역명_clean'] = 이격거리['역명'].apply(clean_station_name)
환승역['역명_clean'] = 환승역['역명'].apply(clean_station_name)
사고['역명_clean'] = 사고['역명_clean'].apply(clean_station_name)

In [ ]:
for name in ['동대문역사문화공원', '교대(2)역', '가락시장역']:
    print(name, '->', clean_station_name(name))

동대문역사문화공원 -> 동대문역사문화공원
교대(2)역 -> 교대
가락시장역 -> 가락시장

In [ ]:
이격거리['호선명']=이격거리['선명']

In [ ]:
이격거리= 이격거리.drop(columns=['선명'], errors='ignore')

In [ ]:
이격거리.head(10)

             역명      구조평균  구조최소  구조최대 역명_clean  호선명
0           동대문  12.66250  10.0  19.0      동대문  1호선
1           동묘앞   6.83750   3.0  12.0      동묘앞  1호선
2           서울역  10.82125   1.5  21.0       서울  1호선
3            시청   9.23750   2.0  15.0       시청  1호선
4           신설동  12.26250   7.0  20.0      신설동  1호선
5           제기동  10.45000   3.0  17.0      제기동  1호선
6            종각   8.85000   7.0  11.0       종각  1호선
7          종로3가   9.38250   2.0  17.0     종로3가  1호선
8          종로5가   9.42500   8.0  11.0     종로5가  1호선
9  청량리(서울시립대입구)   8.60000   4.0  18.0      청량리  1호선

In [ ]:
# 승하차 + 이격거리 병합
df_final = 승하차인원.merge(
    이격거리,
    on=['호선명', '역명_clean'],
    how='left'
)

In [ ]:
df_final = df_final.drop(columns=['지하철역'], errors='ignore')
df_final = df_final.drop(columns=['역명'], errors='ignore')

In [ ]:
df_final.head(50)

       사용월  호선명 time_group       혼잡 역명_clean      구조평균  구조최소  구조최대
0   201502  1호선         기타   169074      동대문  12.66250  10.0  19.0
1   201502  1호선        낮시간   439588      동대문  12.66250  10.0  19.0
2   201502  1호선       출근시간    75265      동대문  12.66250  10.0  19.0
3   201502  1호선       퇴근시간   253230      동대문  12.66250  10.0  19.0
4   201502  1호선         기타    53548      동묘앞   6.83750   3.0  12.0
5   201502  1호선        낮시간   290395      동묘앞   6.83750   3.0  12.0
6   201502  1호선       출근시간    40867      동묘앞   6.83750   3.0  12.0
7   201502  1호선       퇴근시간   158787      동묘앞   6.83750   3.0  12.0
8   201502  1호선         기타   668606       서울  10.82125   1.5  21.0
9   201502  1호선        낮시간  1424527       서울  10.82125   1.5  21.0
10  201502  1호선       출근시간   441209       서울  10.82125   1.5  21.0
11  201502  1호선       퇴근시간  1083328       서울  10.82125   1.5  21.0
12  201502  1호선         기타   208453       시청   9.23750   2.0  15.0
13  201502  1호선        낮시간   434240       시청   9.23750   2.0  15.0
14  201502  1호선       출근시간   219501       시청   9.23750   2.0  15.0
15  201502  1호선       퇴근시간   360070       시청   9.23750   2.0  15.0
16  201502  1호선         기타   135239      신설동  12.26250   7.0  20.0
17  201502  1호선        낮시간   340755      신설동  12.26250   7.0  20.0
18  201502  1호선       출근시간   131454      신설동  12.26250   7.0  20.0
19  201502  1호선       퇴근시간   244813      신설동  12.26250   7.0  20.0
20  201502  1호선         기타    99600      제기동  10.45000   3.0  17.0
21  201502  1호선        낮시간   662289      제기동  10.45000   3.0  17.0
22  201502  1호선       출근시간    97999      제기동  10.45000   3.0  17.0
23  201502  1호선       퇴근시간   295983      제기동  10.45000   3.0  17.0
24  201502  1호선         기타   498110       종각   8.85000   7.0  11.0
25  201502  1호선        낮시간   848052       종각   8.85000   7.0  11.0
26  201502  1호선       출근시간   346452       종각   8.85000   7.0  11.0
27  201502  1호선       퇴근시간   778030       종각   8.85000   7.0  11.0
28  201502  1호선         기타   303313     종로3가   9.38250   2.0  17.0
29  201502  1호선        낮시간   947208     종로3가   9.38250   2.0  17.0
30  201502  1호선       출근시간   124334     종로3가   9.38250   2.0  17.0
31  201502  1호선       퇴근시간   613683     종로3가   9.38250   2.0  17.0
32  201502  1호선         기타   173722     종로5가   9.42500   8.0  11.0
33  201502  1호선        낮시간   684165     종로5가   9.42500   8.0  11.0
34  201502  1호선       출근시간   156013     종로5가   9.42500   8.0  11.0
35  201502  1호선       퇴근시간   467972     종로5가   9.42500   8.0  11.0
36  201502  1호선         기타   270740      청량리   8.60000   4.0  18.0
37  201502  1호선        낮시간   763043      청량리   8.60000   4.0  18.0
38  201502  1호선       출근시간   160477      청량리   8.60000   4.0  18.0
39  201502  1호선       퇴근시간   476506      청량리   8.60000   4.0  18.0
40  201502  2호선         기타  1280824       강남   8.04500   6.5   9.5
41  201502  2호선        낮시간  2115046       강남   8.04500   6.5   9.5
42  201502  2호선       출근시간   627895       강남   8.04500   6.5   9.5
43  201502  2호선       퇴근시간  1802964       강남   8.04500   6.5   9.5
44  201502  2호선         기타   560394       강변   6.95000   4.0  10.0
45  201502  2호선        낮시간  1127781       강변   6.95000   4.0  10.0
46  201502  2호선       출근시간   317542       강변   6.95000   4.0  10.0
47  201502  2호선       퇴근시간   824307       강변   6.95000   4.0  10.0
48  201502  2호선         기타   686808     건대입구   9.04125   7.0  10.5
49  201502  2호선        낮시간   796486     건대입구   9.04125   7.0  10.5

In [ ]:
# 결측 비율 확인하기
print("전체 행 수:", len(df_final))
print("이격거리 안 붙은 행 수:", df_final['구조최대'].isna().sum())
print("이격거리 안 붙은 비율:", df_final['구조최대'].isna().mean())

df_final[df_final['구조최대'].isna()][
    ['호선명',  '역명_clean']
].drop_duplicates().head(50)

전체 행 수: 162316
이격거리 안 붙은 행 수: 4544
이격거리 안 붙은 비율: 0.027994775622859115

        호선명 역명_clean
160     2호선       신천
864     7호선      굴포천
868     7호선      까치울
900     7호선    뚝섬유원지
924     7호선     부천시청
928     7호선  부천종합운동장
932     7호선     부평구청
940     7호선    삼산체육관
948     7호선       상동
968     7호선      신중동
988     7호선       이수
1024    7호선       춘의
114528  4호선      불암산

In [ ]:
missing_stations = (
    df_final[df_final['구조최대'].isna()]
    [['호선명',  '역명_clean']]
    .drop_duplicates()
    .sort_values(['호선명', '역명_clean'])
)

missing_stations.head(50)

        호선명 역명_clean
160     2호선       신천
114528  4호선      불암산
864     7호선      굴포천
868     7호선      까치울
900     7호선    뚝섬유원지
924     7호선     부천시청
928     7호선  부천종합운동장
932     7호선     부평구청
940     7호선    삼산체육관
948     7호선       상동
968     7호선      신중동
988     7호선       이수
1024    7호선       춘의

In [ ]:
missing_stations['호선명'].value_counts()

호선명
7호선    11
2호선     1
4호선     1
Name: count, dtype: int64

In [ ]:
print("이격거리 없는 역 개수:", len(missing_stations))

이격거리 없는 역 개수: 13

In [ ]:
# 구조위험 데이터가 있는 행만 사용
# 이격거리 없는 9호선/일부 구간은 제외
# 구조위험을 포함한 분석용 데이터
df_final_struct = df_final.dropna(subset=['구조최대']).copy()

print(df_final_struct.shape)
print(df_final_struct['구조최대'].isna().sum())

(157772, 8)
0

In [ ]:
# 환승역 데이터 -> transfer_raw 이름 바꿈, 역명 정리, 환승량 생성, 역명 기준 중복 제거
transfer_raw = pd.read_csv(
    '/content/drive/MyDrive/서울시 빅데이터 공모전/data/raw/서울교통공사_환승역환승인원정보_20251130.csv',
    encoding='cp949'
)

# 2) 컬럼/역명 정리
transfer_raw.columns = transfer_raw.columns.str.strip()
transfer_raw['역명'] = transfer_raw['역명'].str.strip()
transfer_raw['역명_clean'] = transfer_raw['역명'].apply(clean_station_name)

# 3) 환승량 생성
transfer_raw['환승량'] = transfer_raw[
    ['평일(일평균)', '토요일', '일요일']
].mean(axis=1)

# 4) 역명 기준 중복 제거
transfer_raw_merge = (
    transfer_raw[['역명_clean', '환승량']]
    .drop_duplicates(subset=['역명_clean'])
)

In [ ]:
transfer_raw.head(10)

   연번         역명  평일(일평균)     토요일     일요일   역명_clean            환승량
0   1        신도림   269275  229757  165107        신도림  221379.666667
1   2  동대문역사문화공원   226341  193636  144058  동대문역사문화공원  188011.666667
2   3      고속터미널   186833  161327  116415      고속터미널  154858.333333
3   4        왕십리   177260  138662   98515        왕십리  138145.666667
4   5        서울역   163998  156550  117615         서울  146054.333333
5   6         사당   160880  138295   97565         사당  132246.666667
6   7       종로3가   153242  147402  101038       종로3가  133894.000000
7   8        충무로   141817  122893   86220        충무로  116976.666667
8   9         교대   138032   98593   65561         교대  100728.666667
9  10         잠실   122968   82219   58534         잠실   87907.000000

In [ ]:
# 1) 사고 자체에 사고수가 있는지 확인
print(사고.head())
print(사고['사고수'].sum())
print(사고.shape)

      사용월  역명_clean  호선명 time_group  사고수
0  202101        공덕  5호선       출근시간    1
1  202101        교대  3호선       퇴근시간    1
2  202101        대림  7호선       출근시간    1
3  202101  동대문사문화공원  2호선        낮시간    1
4  202101        불광  6호선       출근시간    1
1009
(926, 5)

In [ ]:
print(df_final_struct[['사용월','역명_clean','호선명','time_group']].dtypes)
print(사고[['사용월','역명_clean','호선명','time_group']].dtypes)

사용월           object
역명_clean      object
호선명           object
time_group    object
dtype: object
사용월            int64
역명_clean      object
호선명           object
time_group    object
dtype: object

In [ ]:
df_final_struct['사용월'] = pd.to_numeric(df_final_struct['사용월'], errors='coerce').astype('Int64')
사고['사용월'] = pd.to_numeric(사고['사용월'], errors='coerce').astype('Int64')

In [ ]:
for col in ['역명_clean', '호선명', 'time_group']:
    df_final_struct[col] = df_final_struct[col].astype(str).str.strip()
    사고[col] = 사고[col].astype(str).str.strip()

In [ ]:
left_keys = df_final_struct[['사용월','역명_clean','호선명','time_group']].drop_duplicates()
right_keys = 사고[['사용월','역명_clean','호선명','time_group']].drop_duplicates()

matched = left_keys.merge(
    right_keys,
    on=['사용월','역명_clean','호선명','time_group'],
    how='inner'
)

print("겹치는 key 수:", len(matched))
matched.head()

겹치는 key 수: 812

      사용월 역명_clean  호선명 time_group
0  202101       사당  2호선        낮시간
1  202101      충정로  2호선       출근시간
2  202101       합정  2호선       출근시간
3  202101       교대  3호선       퇴근시간
4  202101      연신내  3호선        낮시간

In [ ]:
사고['호선명'] = (
    사고['호선명']
    .astype(str)
    .str.replace('.0호선', '호선', regex=False)
)

In [ ]:
# 기존 사고수 혹시 있으면 제거
df_final_struct = df_final_struct.drop(columns=['사고수'], errors='ignore')

# 사고수 merge
df_final_struct = df_final_struct.merge(
    사고,
    left_on=['사용월', '역명_clean', '호선명', 'time_group'],
    right_on=['사용월', '역명_clean', '호선명', 'time_group'],
    how='left'
)

# 사고 없는 곳은 0
df_final_struct['사고수'] = df_final_struct['사고수'].fillna(0).astype(int)

df_final_struct.head(100)

       사용월  호선명 time_group      혼잡 역명_clean      구조평균  구조최소  구조최대  사고수
0   201502  1호선         기타  169074      동대문  12.66250  10.0  19.0    0
1   201502  1호선        낮시간  439588      동대문  12.66250  10.0  19.0    0
2   201502  1호선       출근시간   75265      동대문  12.66250  10.0  19.0    0
3   201502  1호선       퇴근시간  253230      동대문  12.66250  10.0  19.0    0
4   201502  1호선         기타   53548      동묘앞   6.83750   3.0  12.0    0
..     ...  ...        ...     ...      ...       ...   ...   ...  ...
95  201502  2호선       퇴근시간  298549       방배   7.51875   3.0  16.0    0
96  201502  2호선         기타  271644       봉천   7.67500   3.0  11.0    0
97  201502  2호선        낮시간  438173       봉천   7.67500   3.0  11.0    0
98  201502  2호선       출근시간  206329       봉천   7.67500   3.0  11.0    0
99  201502  2호선       퇴근시간  333042       봉천   7.67500   3.0  11.0    0

[100 rows x 9 columns]

In [ ]:
# 중간 결과 저장
# 현재 중간 결과 저장
df_final_struct.to_csv(
    '/content/drive/MyDrive/서울시 빅데이터 공모전/data/processed/df_final_struct_preprocessed.csv',
    index=False,
    encoding='utf-8-sig'
)

In [ ]:
# B078 컬럼 확인
print(B078.columns.tolist())
B078.head()
B078.info()

['station_name', 'time_group', 'line_name', 'total_pop_sum', 'child_pop_sum', 'youth_pop_sum', 'middle_pop_sum', 'elder_pop_sum']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1232 entries, 0 to 1231
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   station_name    1232 non-null   object
 1   time_group      1232 non-null   object
 2   line_name       1232 non-null   object
 3   total_pop_sum   1232 non-null   float64
 4   child_pop_sum   1232 non-null   float64
 5   youth_pop_sum   1232 non-null   float64
 6   middle_pop_sum  1232 non-null   float64
 7   elder_pop_sum   1232 non-null   float64
dtypes: float64(5), object(3)
memory usage: 77.1+ KB

In [ ]:
# B078 컬럼명 맞추기
B078 = B078.rename(columns={
    'station_name': '지하철역',
    'line_name': '호선명',
    'total_pop_sum': '유입'
})

# 역명 통일
B078['역명_clean'] = B078['지하철역'].apply(clean_station_name)

In [ ]:
# 필요한 컬럼만 선택
B078_merge = B078[
    ['역명_clean', '호선명', 'time_group', '유입',
     'child_pop_sum', 'youth_pop_sum', 'middle_pop_sum', 'elder_pop_sum']
].copy()

In [ ]:
# df_final_struct + B078 병합
df_final_all = df_final_struct.merge(
    B078_merge,
    on=['역명_clean', '호선명', 'time_group'],
    how='left'
)

df_final_all.head()

,사용월,호선명,time_group,혼잡,역명_clean,구조평균,구조최소,구조최대,사고수,유입,child_pop_sum,youth_pop_sum,middle_pop_sum,elder_pop_sum
0,201502,1호선,기타,169074,동대문,12.6625,10.0,19.0,0,109.158033,2.371445,28.573098,38.102411,40.111080
1,201502,1호선,낮시간,439588,동대문,12.6625,10.0,19.0,0,89.818268,4.140349,13.174589,27.672827,44.830502
2,201502,1호선,출근시간,75265,동대문,12.6625,10.0,19.0,0,57.970107,1.030731,8.346038,19.046191,29.547147
3,201502,1호선,퇴근시간,253230,동대문,12.6625,10.0,19.0,0,95.624161,3.856447,21.486049,28.811206,41.470459
4,201502,1호선,기타,53548,동묘앞,6.8375,3.0,12.0,0,70.195318,2.336531,25.357979,22.212263,20.288545

In [ ]:
# 결측 확인
print(df_final_all.shape)
print(df_final_all.isna().sum())

print("B078 유입 안 붙은 비율:", df_final_all['유입'].isna().mean())

(157772, 14)
사용월                  0
호선명                  0
time_group           0
혼잡                   0
역명_clean             0
구조평균                 0
구조최소                 0
구조최대                 0
사고수                  0
유입                2196
child_pop_sum     2196
youth_pop_sum     2196
middle_pop_sum    2196
elder_pop_sum     2196
dtype: int64
B078 유입 안 붙은 비율: 0.013918819562406511

In [ ]:
# 결측이 어떤 역인지 확인
df_final_all[df_final_all['유입'].isna()][
    ['호선명', '역명_clean', 'time_group']
].drop_duplicates().head(100)

       호선명 역명_clean time_group
308    3호선       신사         기타
309    3호선       신사        낮시간
310    3호선       신사       출근시간
311    3호선       신사       퇴근시간
384    4호선      당고개         기타
385    4호선      당고개        낮시간
386    4호선      당고개       출근시간
387    4호선      당고개       퇴근시간
684    6호선       공덕         기타
685    6호선       공덕        낮시간
686    6호선       공덕       출근시간
687    6호선       공덕       퇴근시간
1124   9호선      신논현         기타
1125   9호선      신논현        낮시간
1126   9호선      신논현       출근시간
1127   9호선      신논현       퇴근시간
96416  7호선       자양         기타
96417  7호선       자양        낮시간
96418  7호선       자양       출근시간
96419  7호선       자양       퇴근시간

In [ ]:
B078[B078['역명_clean'].str.contains('신사|당고개|공덕|신논현|자양', na=False)][
    ['호선명', '지하철역', '역명_clean', 'time_group', '유입']
].drop_duplicates()

    호선명 지하철역 역명_clean time_group          유입
92  5호선   공덕       공덕         기타  110.693211
93  5호선   공덕       공덕        낮시간   89.265436
94  5호선   공덕       공덕       출근시간   57.260481
95  5호선   공덕       공덕       퇴근시간   97.841149

In [ ]:
# 결측 5개 역밖에 없으니까 그냥 0으로 채우기
df_final_all['유입'] = df_final_all['유입'].fillna(0)

for col in ['child_pop_sum', 'youth_pop_sum', 'middle_pop_sum', 'elder_pop_sum']:
    df_final_all[col] = df_final_all[col].fillna(0)

In [ ]:
# 확인
print(df_final_all.isna().sum())

사용월               0
호선명               0
time_group        0
혼잡                0
역명_clean          0
구조평균              0
구조최소              0
구조최대              0
사고수               0
유입                0
child_pop_sum     0
youth_pop_sum     0
middle_pop_sum    0
elder_pop_sum     0
dtype: int64

In [ ]:
# 5) 기존 환승량 있으면 제거 후 병합
df_model = df_final_all.drop(columns=['환승량'], errors='ignore')

df_model = df_final_all.merge(
    transfer_raw_merge,
    on='역명_clean',
    how='left'
)

# 6) 비환승역은 환승량 0
df_model['환승량'] = df_model['환승량'].fillna(0)

# 확인
print(df_model[['역명_clean', '환승량']].drop_duplicates().head(30))
print(df_model.isna().sum())

      역명_clean            환승량
0          동대문   48535.333333
4          동묘앞   45053.333333
8           서울  146054.333333
12          시청   44332.333333
16         신설동   32792.666667
20         제기동       0.000000
24          종각       0.000000
28        종로3가  133894.000000
32        종로5가       0.000000
36         청량리   25778.333333
40          강남   45664.000000
44          강변       0.000000
48        건대입구   91910.333333
52          교대  100728.666667
56     구로디지털단지       0.000000
60          구의       0.000000
64         낙성대       0.000000
68          당산   55554.000000
72          대림   56852.666667
76         도림천       0.000000
80   동대문역사문화공원  188011.666667
84          뚝섬       0.000000
88          문래       0.000000
92          방배       0.000000
96          봉천       0.000000
100         사당  132246.666667
104         삼성       0.000000
108       상왕십리       0.000000
112      서울대입구       0.000000
116         서초       0.000000
사용월               0
호선명               0
time_group        0
혼잡                0
역명_clean          0
구조평균              0
구조최소              0
구조최대              0
사고수               0
유입                0
child_pop_sum     0
youth_pop_sum     0
middle_pop_sum    0
elder_pop_sum     0
환승량               0
dtype: int64

In [ ]:
df_model.columns

Index(['사용월', '호선명', 'time_group', '혼잡', '역명_clean', '구조평균', '구조최소', '구조최대',
       '사고수', '유입', 'child_pop_sum', 'youth_pop_sum', 'middle_pop_sum',
       'elder_pop_sum', '환승량'],
      dtype='object')

In [ ]:
[col for col in df_model.columns if '_x' in col or '_y' in col]

[]

In [ ]:
print(df_model.isna().sum())

사용월               0
호선명               0
time_group        0
혼잡                0
역명_clean          0
구조평균              0
구조최소              0
구조최대              0
사고수               0
유입                0
child_pop_sum     0
youth_pop_sum     0
middle_pop_sum    0
elder_pop_sum     0
환승량               0
dtype: int64

In [ ]:
df_model.duplicated(
    subset=['사용월', '호선명', '역명_clean', 'time_group']
).sum()

np.int64(0)

In [ ]:
df_model.head(20)

,사용월,호선명,time_group,혼잡,역명_clean,구조평균,구조최소,구조최대,사고수,유입,child_pop_sum,youth_pop_sum,middle_pop_sum,elder_pop_sum,환승량
0,201502,1호선,기타,169074,동대문,12.66250,10.0,19.0,0,109.158033,2.371445,28.573098,38.102411,40.111080,48535.333333
1,201502,1호선,낮시간,439588,동대문,12.66250,10.0,19.0,0,89.818268,4.140349,13.174589,27.672827,44.830502,48535.333333
2,201502,1호선,출근시간,75265,동대문,12.66250,10.0,19.0,0,57.970107,1.030731,8.346038,19.046191,29.547147,48535.333333
3,201502,1호선,퇴근시간,253230,동대문,12.66250,10.0,19.0,0,95.624161,3.856447,21.486049,28.811206,41.470459,48535.333333
4,201502,1호선,기타,53548,동묘앞,6.83750,3.0,12.0,0,70.195318,2.336531,25.357979,22.212263,20.288545,45053.333333
5,201502,1호선,낮시간,290395,동묘앞,6.83750,3.0,12.0,0,59.571030,2.421803,11.906279,18.392318,26.850630,45053.333333
6,201502,1호선,출근시간,40867,동묘앞,6.83750,3.0,12.0,0,37.758642,0.627182,8.560263,14.044943,14.526254,45053.333333
7,201502,1호선,퇴근시간,158787,동묘앞,6.83750,3.0,12.0,0,63.048366,3.533937,19.791535,19.631047,20.091848,45053.333333
8,201502,1호선,기타,668606,서울,10.82125,1.5,21.0,0,34.795002,2.768720,13.940185,10.029385,8.056711,146054.333333
9,201502,1호선,낮시간,1424527,서울,10.82125,1.5,21.0,0,29.593260,1.310507,8.826405,10.836272,8.620076,146054.333333
10,201502,1호선,출근시간,441209,서울,10.82125,1.5,21.0,0,19.041292,0.532163,6.613859,8.449918,3.445352,146054.333333
11,201502,1호선,퇴근시간,1083328,서울,10.82125,1.5,21.0,0,32.496973,2.171820,12.750873,11.111084,6.463195,146054.333333
12,201502,1호선,기타,208453,시청,9.23750,2.0,15.0,0,104.907779,1.937631,30.402931,40.012374,32.554844,44332.333333
13,201502,1호선,낮시간,434240,시청,9.23750,2.0,15.0,0,96.019118,2.773558,32.298710,41.572589,19.374261,44332.333333
14,201502,1호선,출근시간,219501,시청,9.23750,2.0,15.0,0,57.860081,1.122998,19.434281,30.139463,7.163339,44332.333333
15,201502,1호선,퇴근시간,360070,시청,9.23750,2.0,15.0,0,100.625589,3.159573,34.112320,38.744503,24.609194,44332.333333
16,201502,1호선,기타,135239,신설동,12.26250,7.0,20.0,0,36.836019,0.885346,16.717579,11.810446,7.422648,32792.666667
17,201502,1호선,낮시간,340755,신설동,12.26250,7.0,20.0,0,29.753143,0.495640,8.206439,9.763046,11.288017,32792.666667
18,201502,1호선,출근시간,131454,신설동,12.26250,7.0,20.0,0,19.729683,0.117719,6.762842,8.716390,4.132732,32792.666667
19,201502,1호선,퇴근시간,244813,신설동,12.26250,7.0,20.0,0,33.160411,0.952457,13.650944,10.737977,7.819033,32792.666667

In [ ]:
df_model.head()

,사용월,호선명,time_group,혼잡,역명_clean,구조평균,구조최소,구조최대,사고수,유입,child_pop_sum,youth_pop_sum,middle_pop_sum,elder_pop_sum,환승량
0,201502,1호선,기타,169074,동대문,12.6625,10.0,19.0,0,109.158033,2.371445,28.573098,38.102411,40.111080,48535.333333
1,201502,1호선,낮시간,439588,동대문,12.6625,10.0,19.0,0,89.818268,4.140349,13.174589,27.672827,44.830502,48535.333333
2,201502,1호선,출근시간,75265,동대문,12.6625,10.0,19.0,0,57.970107,1.030731,8.346038,19.046191,29.547147,48535.333333
3,201502,1호선,퇴근시간,253230,동대문,12.6625,10.0,19.0,0,95.624161,3.856447,21.486049,28.811206,41.470459,48535.333333
4,201502,1호선,기타,53548,동묘앞,6.8375,3.0,12.0,0,70.195318,2.336531,25.357979,22.212263,20.288545,45053.333333

In [ ]:
df_model['사용월'] = pd.to_numeric(df_model['사용월'], errors='coerce')

In [ ]:
df_model = df_model[df_model['사용월'] >= 202101].copy()

In [ ]:
print(df_model['사용월'].dtype)

Int64

In [ ]:
df_model.tail(50)

,사용월,호선명,time_group,혼잡,역명_clean,구조평균,구조최소,구조최대,사고수,유입,child_pop_sum,youth_pop_sum,middle_pop_sum,elder_pop_sum,환승량
124158,202602,9호선,출근시간,302934,여의도,5.483333,4.9,6.8,0,37.836090,0.297723,16.604809,17.562124,3.371434,45536.000000
124159,202602,9호선,퇴근시간,507486,여의도,5.483333,4.9,6.8,0,64.981390,2.454150,26.273638,26.314750,9.938852,45536.000000
124160,202602,9호선,기타,182388,염창,7.195833,5.0,9.7,0,163.988582,11.017363,68.153961,51.052519,33.764739,0.000000
124161,202602,9호선,낮시간,281307,염창,7.195833,5.0,9.7,0,132.064153,9.118197,37.158666,45.946057,39.841233,0.000000
124162,202602,9호선,출근시간,162932,염창,7.195833,5.0,9.7,0,83.082573,3.312073,24.946282,31.913389,22.910828,0.000000
124163,202602,9호선,퇴근시간,259613,염창,7.195833,5.0,9.7,0,142.827739,11.096403,53.735996,48.761273,29.234067,0.000000
124164,202602,9호선,기타,52597,증미,6.464583,5.0,8.0,0,184.375782,5.925160,69.158248,73.786825,35.505549,0.000000
124165,202602,9호선,낮시간,114381,증미,6.464583,5.0,8.0,0,157.036122,4.229471,48.335791,65.508622,38.962238,0.000000
124166,202602,9호선,출근시간,90418,증미,6.464583,5.0,8.0,0,100.532342,1.646011,32.460552,46.495101,19.930678,0.000000
124167,202602,9호선,퇴근시간,118649,증미,6.464583,5.0,8.0,0,172.015917,5.263936,61.264368,73.925472,31.562141,0.000000
124168,202602,9호선,기타,75376,흑석,7.570833,5.0,9.9,0,187.263749,13.361454,61.205010,62.536172,50.161112,0.000000
124169,202602,9호선,낮시간,174032,흑석,7.570833,5.0,9.9,0,155.936192,12.571918,36.425773,50.209467,56.729034,0.000000
124170,202602,9호선,출근시간,61624,흑석,7.570833,5.0,9.9,0,100.077428,8.354845,20.258746,34.089062,37.374775,0.000000
124171,202602,9호선,퇴근시간,132841,흑석,7.570833,5.0,9.9,0,168.261923,12.636910,55.086981,58.530805,42.007227,0.000000
157736,202102,1호선,기타,35084,동묘앞,6.837500,3.0,12.0,0,70.195318,2.336531,25.357979,22.212263,20.288545,45053.333333
157737,202102,1호선,낮시간,267266,동묘앞,6.837500,3.0,12.0,0,59.571030,2.421803,11.906279,18.392318,26.850630,45053.333333
157738,202102,1호선,출근시간,30600,동묘앞,6.837500,3.0,12.0,0,37.758642,0.627182,8.560263,14.044943,14.526254,45053.333333
157739,202102,1호선,퇴근시간,120362,동묘앞,6.837500,3.0,12.0,0,63.048366,3.533937,19.791535,19.631047,20.091848,45053.333333
157740,202102,1호선,기타,248145,서울,10.821250,1.5,21.0,0,34.795002,2.768720,13.940185,10.029385,8.056711,146054.333333
157741,202102,1호선,낮시간,651334,서울,10.821250,1.5,21.0,0,29.593260,1.310507,8.826405,10.836272,8.620076,146054.333333
157742,202102,1호선,출근시간,275443,서울,10.821250,1.5,21.0,0,19.041292,0.532163,6.613859,8.449918,3.445352,146054.333333
157743,202102,1호선,퇴근시간,547718,서울,10.821250,1.5,21.0,0,32.496973,2.171820,12.750873,11.111084,6.463195,146054.333333
157744,202102,1호선,기타,114874,시청,9.237500,2.0,15.0,0,104.907779,1.937631,30.402931,40.012374,32.554844,44332.333333
157745,202102,1호선,낮시간,269605,시청,9.237500,2.0,15.0,0,96.019118,2.773558,32.298710,41.572589,19.374261,44332.333333
157746,202102,1호선,출근시간,181569,시청,9.237500,2.0,15.0,0,57.860081,1.122998,19.434281,30.139463,7.163339,44332.333333
157747,202102,1호선,퇴근시간,267725,시청,9.237500,2.0,15.0,0,100.625589,3.159573,34.112320,38.744503,24.609194,44332.333333
157748,202102,1호선,기타,208562,종각,8.850000,7.0,11.0,0,172.972044,7.703194,80.262008,57.026455,27.980386,0.000000
157749,202102,1호선,낮시간,466567,종각,8.850000,7.0,11.0,0,161.655283,5.952795,67.360618,60.072680,28.269190,0.000000
157750,202102,1호선,출근시간,244197,종각,8.850000,7.0,11.0,0,92.668885,0.971728,39.575722,38.899495,13.221939,0.000000
157751,202102,1호선,퇴근시간,449317,종각,8.850000,7.0,11.0,0,173.041344,8.647153,88.076669,58.320581,17.996941,0.000000
157752,202102,6호선,기타,2,연신내,14.812500,10.0,17.0,0,115.920139,6.571589,57.203468,33.348166,18.796917,28193.666667
157753,202102,6호선,낮시간,11,연신내,14.812500,10.0,17.0,0,96.658938,13.034478,28.467584,27.253986,27.902889,28193.666667
157754,202102,6호선,출근시간,1,연신내,14.812500,10.0,17.0,0,60.672823,6.656785,18.170587,19.617220,16.228230,28193.666667
157755,202102,6호선,퇴근시간,1,연신내,14.812500,10.0,17.0,0,102.659036,10.347261,46.273730,29.003942,17.034103,28193.666667
157756,202201,3호선,기타,8,충무로,11.600000,3.0,26.0,0,65.396704,1.560777,19.024552,24.550529,20.260845,116976.666667
157757,202201,3호선,낮시간,2,충무로,11.600000,3.0,26.0,0,58.444158,0.954160,12.526009,22.155167,22.808823,116976.666667
157758,202201,3호선,출근시간,0,충무로,11.600000,3.0,26.0,1,37.733675,0.143915,7.469831,12.614039,17.505889,116976.666667
157759,202201,3호선,퇴근시간,9,충무로,11.600000,3.0,26.0,0,62.635561,1.418717,19.719103,25.280537,16.217205,116976.666667
157760,202201,6호선,기타,0,신내,8.000000,8.0,8.0,0,113.111270,6.583008,42.225976,41.887499,22.414786,7709.333333
157761,202201,6호선,낮시간,2,신내,8.000000,8.0,8.0,0,92.137277,3.513050,19.650579,36.996303,31.977345,7709.333333
157762,202201,6호선,출근시간,1,신내,8.000000,8.0,8.0,0,59.312633,1.312436,13.558564,26.252268,18.189365,7709.333333
157763,202201,6호선,퇴근시간,2,신내,8.000000,8.0,8.0,0,100.391797,5.618498,31.184153,39.658508,23.930638,7709.333333
157764,202203,6호선,기타,6,연신내,14.812500,10.0,17.0,0,115.920139,6.571589,57.203468,33.348166,18.796917,28193.666667
157765,202203,6호선,낮시간,9,연신내,14.812500,10.0,17.0,0,96.658938,13.034478,28.467584,27.253986,27.902889,28193.666667
157766,202203,6호선,출근시간,3,연신내,14.812500,10.0,17.0,0,60.672823,6.656785,18.170587,19.617220,16.228230,28193.666667
157767,202203,6호선,퇴근시간,3,연신내,14.812500,10.0,17.0,0,102.659036,10.347261,46.273730,29.003942,17.034103,28193.666667
157768,202503,3호선,기타,27,충무로,11.600000,3.0,26.0,0,65.396704,1.560777,19.024552,24.550529,20.260845,116976.666667
157769,202503,3호선,낮시간,52,충무로,11.600000,3.0,26.0,0,58.444158,0.954160,12.526009,22.155167,22.808823,116976.666667
157770,202503,3호선,출근시간,3,충무로,11.600000,3.0,26.0,0,37.733675,0.143915,7.469831,12.614039,17.505889,116976.666667
157771,202503,3호선,퇴근시간,66,충무로,11.600000,3.0,26.0,0,62.635561,1.418717,19.719103,25.280537,16.217205,116976.666667

In [ ]:
# 최최종 저장
df_model.to_csv(
    '/content/drive/MyDrive/서울시 빅데이터 공모전/data/processed/df_final_all_preprocessed.csv',
    index=False,
    encoding='utf-8-sig'
)