In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# 기본

In [ ]:
# 라이브러리 불러오기 + 데이터 로드
import pandas as pd

file_path = '/content/drive/MyDrive/서울시 빅데이터 공모전/data/processed/subway_risk_result.csv'
df = pd.read_csv(file_path, encoding='utf-8-sig')
df.head()

,역명_clean,호선명,time_group,Risk_Score,Risk,사고수,사고발생,위험유형,주요위험원인,혼잡기여도,유입기여도,구조기여도,환승기여도,추천대응전략
0,사당,2호선,퇴근시간,89.612410,0.896124,11,1,환승형,환승형,17.577361,16.471606,24.676271,41.274762,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
1,사당,2호선,낮시간,89.576990,0.895770,12,1,환승형,환승형,17.273867,15.784539,25.046900,41.894694,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
2,사당,4호선,낮시간,89.482670,0.894827,8,1,환승형,환승형,11.508750,25.662743,19.450347,43.378160,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
3,종로3가,1호선,낮시간,89.417564,0.894176,4,1,구조형,구조형,12.316445,19.858253,33.977756,33.847546,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
4,신도림,2호선,낮시간,89.229870,0.892299,10,1,환승형,환승형,17.240165,11.438121,15.067968,56.253747,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"

In [ ]:
# 컬럼 확인
df.columns

Index(['역명_clean', '호선명', 'time_group', 'Risk_Score', 'Risk', '사고수', '사고발생',
       '위험유형', '주요위험원인', '혼잡기여도', '유입기여도', '구조기여도', '환승기여도', '추천대응전략'],
      dtype='object')

# 전체 위험구간 Top 20

In [ ]:
# 전체 위험구간 Top 20 추출
# Risk Score가 높은 역·호선·시간대 조합을 확인

top20_risk = (
    df.sort_values('Risk_Score', ascending=False)
      .head(20)
      .reset_index(drop=True)
)

display_cols = [
    '역명_clean',
    '호선명',
    'time_group',
    'Risk_Score',
    '위험유형',
    '주요위험원인',
    '추천대응전략'
]

top20_risk[display_cols]

,역명_clean,호선명,time_group,Risk_Score,위험유형,주요위험원인,추천대응전략
0,사당,2호선,퇴근시간,89.612410,환승형,환승형,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
1,사당,2호선,낮시간,89.576990,환승형,환승형,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
2,사당,4호선,낮시간,89.482670,환승형,환승형,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
3,종로3가,1호선,낮시간,89.417564,구조형,구조형,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
4,신도림,2호선,낮시간,89.229870,환승형,환승형,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
5,고속터미널,7호선,낮시간,88.969870,환승형,환승형,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
6,사당,4호선,퇴근시간,88.902620,환승형,환승형,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
7,신도림,2호선,퇴근시간,88.441670,환승형,환승형,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
8,충무로,4호선,낮시간,88.061240,구조형,구조형,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
9,잠실,2호선,낮시간,87.898600,구조형,구조형,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
10,종로3가,1호선,퇴근시간,87.883630,구조형,구조형,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
11,서울,1호선,퇴근시간,87.639900,구조형,구조형,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
12,충무로,3호선,낮시간,87.396320,구조형,구조형,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
13,충무로,3호선,출근시간,87.206570,구조형,구조형,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
14,고속터미널,3호선,낮시간,87.195496,환승형,환승형,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
15,충무로,4호선,퇴근시간,87.097140,구조형,구조형,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
16,사당,2호선,기타,87.084410,환승형,환승형,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
17,잠실,2호선,퇴근시간,87.041490,유입형,유입형,"출입구 혼잡 관리, 피크시간 안전요원 배치, 유입 인구 분산 안내"
18,연신내,3호선,낮시간,86.782570,구조형,구조형,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
19,서울,1호선,낮시간,86.613620,구조형,구조형,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"

In [ ]:
# 순위 컬럼 추가
top20_table = top20_risk[display_cols].copy()

top20_table.insert(0, '순위', range(1, len(top20_table) + 1))

top20_table

,순위,역명_clean,호선명,time_group,Risk_Score,위험유형,주요위험원인,추천대응전략
0,1,사당,2호선,퇴근시간,89.612410,환승형,환승형,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
1,2,사당,2호선,낮시간,89.576990,환승형,환승형,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
2,3,사당,4호선,낮시간,89.482670,환승형,환승형,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
3,4,종로3가,1호선,낮시간,89.417564,구조형,구조형,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
4,5,신도림,2호선,낮시간,89.229870,환승형,환승형,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
5,6,고속터미널,7호선,낮시간,88.969870,환승형,환승형,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
6,7,사당,4호선,퇴근시간,88.902620,환승형,환승형,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
7,8,신도림,2호선,퇴근시간,88.441670,환승형,환승형,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
8,9,충무로,4호선,낮시간,88.061240,구조형,구조형,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
9,10,잠실,2호선,낮시간,87.898600,구조형,구조형,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
10,11,종로3가,1호선,퇴근시간,87.883630,구조형,구조형,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
11,12,서울,1호선,퇴근시간,87.639900,구조형,구조형,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
12,13,충무로,3호선,낮시간,87.396320,구조형,구조형,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
13,14,충무로,3호선,출근시간,87.206570,구조형,구조형,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
14,15,고속터미널,3호선,낮시간,87.195496,환승형,환승형,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
15,16,충무로,4호선,퇴근시간,87.097140,구조형,구조형,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
16,17,사당,2호선,기타,87.084410,환승형,환승형,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
17,18,잠실,2호선,퇴근시간,87.041490,유입형,유입형,"출입구 혼잡 관리, 피크시간 안전요원 배치, 유입 인구 분산 안내"
18,19,연신내,3호선,낮시간,86.782570,구조형,구조형,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
19,20,서울,1호선,낮시간,86.613620,구조형,구조형,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"

In [ ]:
# 주요 위험원인 표현정리
# 예: 환승형 -> 환승 요인
top20_table['주요위험원인'] = (
    top20_table['주요위험원인']
    .astype(str)
    .str.replace('형', ' 요인')
)

top20_table

,순위,역명_clean,호선명,time_group,Risk_Score,위험유형,주요위험원인,추천대응전략
0,1,사당,2호선,퇴근시간,89.612410,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
1,2,사당,2호선,낮시간,89.576990,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
2,3,사당,4호선,낮시간,89.482670,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
3,4,종로3가,1호선,낮시간,89.417564,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
4,5,신도림,2호선,낮시간,89.229870,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
5,6,고속터미널,7호선,낮시간,88.969870,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
6,7,사당,4호선,퇴근시간,88.902620,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
7,8,신도림,2호선,퇴근시간,88.441670,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
8,9,충무로,4호선,낮시간,88.061240,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
9,10,잠실,2호선,낮시간,87.898600,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
10,11,종로3가,1호선,퇴근시간,87.883630,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
11,12,서울,1호선,퇴근시간,87.639900,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
12,13,충무로,3호선,낮시간,87.396320,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
13,14,충무로,3호선,출근시간,87.206570,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
14,15,고속터미널,3호선,낮시간,87.195496,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
15,16,충무로,4호선,퇴근시간,87.097140,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
16,17,사당,2호선,기타,87.084410,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
17,18,잠실,2호선,퇴근시간,87.041490,유입형,유입 요인,"출입구 혼잡 관리, 피크시간 안전요원 배치, 유입 인구 분산 안내"
18,19,연신내,3호선,낮시간,86.782570,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
19,20,서울,1호선,낮시간,86.613620,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"

In [ ]:
# Risk Score 소수점 정리
top20_table['Risk_Score'] = top20_table['Risk_Score'].round(1)

top20_table

,순위,역명_clean,호선명,time_group,Risk_Score,위험유형,주요위험원인,추천대응전략
0,1,사당,2호선,퇴근시간,89.6,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
1,2,사당,2호선,낮시간,89.6,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
2,3,사당,4호선,낮시간,89.5,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
3,4,종로3가,1호선,낮시간,89.4,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
4,5,신도림,2호선,낮시간,89.2,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
5,6,고속터미널,7호선,낮시간,89.0,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
6,7,사당,4호선,퇴근시간,88.9,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
7,8,신도림,2호선,퇴근시간,88.4,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
8,9,충무로,4호선,낮시간,88.1,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
9,10,잠실,2호선,낮시간,87.9,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
10,11,종로3가,1호선,퇴근시간,87.9,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
11,12,서울,1호선,퇴근시간,87.6,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
12,13,충무로,3호선,낮시간,87.4,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
13,14,충무로,3호선,출근시간,87.2,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
14,15,고속터미널,3호선,낮시간,87.2,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
15,16,충무로,4호선,퇴근시간,87.1,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
16,17,사당,2호선,기타,87.1,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
17,18,잠실,2호선,퇴근시간,87.0,유입형,유입 요인,"출입구 혼잡 관리, 피크시간 안전요원 배치, 유입 인구 분산 안내"
18,19,연신내,3호선,낮시간,86.8,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
19,20,서울,1호선,낮시간,86.6,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"

In [ ]:
# 최종 Top 20 표
top20_table

,순위,역명_clean,호선명,time_group,Risk_Score,위험유형,주요위험원인,추천대응전략
0,1,사당,2호선,퇴근시간,89.6,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
1,2,사당,2호선,낮시간,89.6,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
2,3,사당,4호선,낮시간,89.5,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
3,4,종로3가,1호선,낮시간,89.4,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
4,5,신도림,2호선,낮시간,89.2,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
5,6,고속터미널,7호선,낮시간,89.0,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
6,7,사당,4호선,퇴근시간,88.9,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
7,8,신도림,2호선,퇴근시간,88.4,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
8,9,충무로,4호선,낮시간,88.1,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
9,10,잠실,2호선,낮시간,87.9,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
10,11,종로3가,1호선,퇴근시간,87.9,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
11,12,서울,1호선,퇴근시간,87.6,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
12,13,충무로,3호선,낮시간,87.4,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
13,14,충무로,3호선,출근시간,87.2,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
14,15,고속터미널,3호선,낮시간,87.2,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
15,16,충무로,4호선,퇴근시간,87.1,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
16,17,사당,2호선,기타,87.1,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
17,18,잠실,2호선,퇴근시간,87.0,유입형,유입 요인,"출입구 혼잡 관리, 피크시간 안전요원 배치, 유입 인구 분산 안내"
18,19,연신내,3호선,낮시간,86.8,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
19,20,서울,1호선,낮시간,86.6,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"

In [ ]:
# 해석:
# 전체 위험구간 TOP 20 분석 결과, 사당·신도림·고속터미널과 같은 주요 환승 거점역이 상위권에 다수 포함되었다.
# 특히 사당역 2호선 퇴근시간의 Risk Score가 89.6점으로 가장 높게 나타났으며,
# 이는 환승 동선 복잡성과 이용객 집중이 복합적으로 작용한 결과로 해석된다.
#
# 또한 종로3가, 충무로, 서울역 등은 구조형 위험으로 분류되었다.
# 이는 단순히 이용객 수가 많은 역뿐 아니라 승강장 구조, 환승 연결 방식,
# 보행 동선 등 물리적 환경 요인도 사고위험에 중요한 영향을 미친다는 것을 보여준다.
#
# 따라서 모든 역에 동일한 안전대책을 적용하기보다,
# 환승형 역에는 환승 동선 분리와 안전요원 배치를,
# 구조형 역에는 승강장 유도선 정비와 안전표지 보강을 우선 적용할 필요가 있다.

In [ ]:
# 저장
'''
save_path = '/content/drive/MyDrive/서울시 빅데이터 공모전/data/processed/top20_risk_sections.csv'
top20_table.to_csv(save_path, index=False, encoding='utf-8-sig')
print("저장 완료:", save_path)
'''

# 위험유형별 Top10

In [ ]:
# 위험유형별 Top 10 분석
# 위험유형별로 가장 위험도가 높은 역, 호선, 시간대를 확인
def get_top10_by_risk_type(risk_type):
    result = (
        df[df['위험유형'] == risk_type]
        .sort_values('Risk_Score', ascending=False)
        .head(10)
        .reset_index(drop=True)
    )

    display_cols = [
        '역명_clean',
        '호선명',
        'time_group',
        'Risk_Score',
        '위험유형',
        '주요위험원인',
        '추천대응전략'
    ]

    result_table = result[display_cols].copy()
    result_table.insert(0, '순위', range(1, len(result_table) + 1))

    result_table['주요위험원인'] = (
        result_table['주요위험원인']
        .astype(str)
        .str.replace('형', ' 요인')
    )

    result_table['Risk_Score'] = result_table['Risk_Score'].round(1)

    return result_table

In [ ]:
get_top10_by_risk_type('환승형')

,순위,역명_clean,호선명,time_group,Risk_Score,위험유형,주요위험원인,추천대응전략
0,1,사당,2호선,퇴근시간,89.6,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
1,2,사당,2호선,낮시간,89.6,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
2,3,사당,4호선,낮시간,89.5,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
3,4,신도림,2호선,낮시간,89.2,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
4,5,고속터미널,7호선,낮시간,89.0,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
5,6,사당,4호선,퇴근시간,88.9,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
6,7,신도림,2호선,퇴근시간,88.4,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
7,8,고속터미널,3호선,낮시간,87.2,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
8,9,사당,2호선,기타,87.1,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"
9,10,고속터미널,3호선,퇴근시간,86.5,환승형,환승 요인,"환승 동선 분리, 환승 통로 안전요원 배치, 환승 안내 표지 강화"

In [ ]:
get_top10_by_risk_type('구조형')

,순위,역명_clean,호선명,time_group,Risk_Score,위험유형,주요위험원인,추천대응전략
0,1,종로3가,1호선,낮시간,89.4,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
1,2,충무로,4호선,낮시간,88.1,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
2,3,잠실,2호선,낮시간,87.9,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
3,4,종로3가,1호선,퇴근시간,87.9,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
4,5,서울,1호선,퇴근시간,87.6,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
5,6,충무로,3호선,낮시간,87.4,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
6,7,충무로,3호선,출근시간,87.2,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
7,8,충무로,4호선,퇴근시간,87.1,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
8,9,연신내,3호선,낮시간,86.8,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"
9,10,서울,1호선,낮시간,86.6,구조형,구조 요인,"승강장 유도선 정비, 안전표지 보강, 시설 구조 점검"

In [ ]:
get_top10_by_risk_type('유입형')

,순위,역명_clean,호선명,time_group,Risk_Score,위험유형,주요위험원인,추천대응전략
0,1,잠실,2호선,퇴근시간,87.0,유입형,유입 요인,"출입구 혼잡 관리, 피크시간 안전요원 배치, 유입 인구 분산 안내"
1,2,교대,2호선,낮시간,86.3,유입형,유입 요인,"출입구 혼잡 관리, 피크시간 안전요원 배치, 유입 인구 분산 안내"
2,3,교대,2호선,퇴근시간,85.9,유입형,유입 요인,"출입구 혼잡 관리, 피크시간 안전요원 배치, 유입 인구 분산 안내"
3,4,잠실,2호선,기타,83.6,유입형,유입 요인,"출입구 혼잡 관리, 피크시간 안전요원 배치, 유입 인구 분산 안내"
4,5,건대입구,2호선,기타,83.6,유입형,유입 요인,"출입구 혼잡 관리, 피크시간 안전요원 배치, 유입 인구 분산 안내"
5,6,노원,7호선,낮시간,81.4,유입형,유입 요인,"출입구 혼잡 관리, 피크시간 안전요원 배치, 유입 인구 분산 안내"
6,7,대림,2호선,낮시간,80.1,유입형,유입 요인,"출입구 혼잡 관리, 피크시간 안전요원 배치, 유입 인구 분산 안내"
7,8,대림,7호선,낮시간,79.7,유입형,유입 요인,"출입구 혼잡 관리, 피크시간 안전요원 배치, 유입 인구 분산 안내"
8,9,공덕,5호선,퇴근시간,78.4,유입형,유입 요인,"출입구 혼잡 관리, 피크시간 안전요원 배치, 유입 인구 분산 안내"
9,10,잠실,8호선,퇴근시간,76.2,유입형,유입 요인,"출입구 혼잡 관리, 피크시간 안전요원 배치, 유입 인구 분산 안내"

In [ ]:
get_top10_by_risk_type('혼잡형')

,순위,역명_clean,호선명,time_group,Risk_Score,위험유형,주요위험원인,추천대응전략
0,1,강남,2호선,낮시간,33.2,혼잡형,혼잡 요인,"혼잡 알림 제공, 승강장 질서유지 인력 배치, 배차 간격 조정 검토"

In [ ]:
# 해석:
# 위험유형별 TOP 10 분석 결과, 환승형은 사당·신도림·고속터미널 등
# 대표적인 환승 거점역에 집중되어 나타났다.
# 이는 환승 동선 복잡성과 이용객 집중이 주요 위험요인으로 작용함을 의미한다.
#
# 구조형은 종로3가·충무로·서울역 등에서 높게 나타났다.
# 이는 단순 혼잡보다 승강장 구조, 보행 동선, 시설 환경과 같은
# 물리적 요인이 사고위험에 크게 작용할 수 있음을 보여준다.
#
# 유입형은 잠실·교대·건대입구·노원 등 외부 유입 인구가 많은 역에서 나타났다.
# 따라서 출입구 혼잡 관리, 피크시간 안전요원 배치, 유입 인구 분산 안내가 필요하다.
#
# 혼잡형은 강남역 2호선 낮시간 1개 구간만 확인되었다.
# 이는 본 데이터에서 단순 혼잡 요인보다 환승·구조·유입 요인이
# 상대적으로 더 큰 위험요인으로 분류되었음을 의미한다.

# 시간대별 위험 패턴

In [ ]:
# 시간대별 위험 패턴 분석
# 시간대별 평균 Risk Score와 고위험 구간 수를 확인
time_pattern = (
    df.groupby('time_group')
      .agg(
          평균위험도=('Risk_Score', 'mean'),
          최대위험도=('Risk_Score', 'max'),
          구간수=('Risk_Score', 'count'),
          고위험구간수=('Risk_Score', lambda x: (x >= 80).sum())
      )
      .reset_index()
)

time_pattern['평균위험도'] = time_pattern['평균위험도'].round(1)
time_pattern['최대위험도'] = time_pattern['최대위험도'].round(1)

time_pattern

  time_group  평균위험도  최대위험도  구간수  고위험구간수
0         기타   17.1   87.1  300       6
1        낮시간   25.5   89.6  300      29
2       출근시간   23.0   87.2  300      10
3       퇴근시간   24.2   89.6  300      21

In [ ]:
# 해석:
# 시간대별 평균위험도는 낮시간이 25.5점으로 가장 높게 나타났고,
# 퇴근시간 24.2점, 출근시간 23.0점, 기타 17.1점 순으로 나타났다.
#
# 고위험구간수는 낮시간이 29개로 가장 많았고,
# 퇴근시간이 21개, 출근시간이 10개, 기타가 6개로 나타났다.
#
# 이는 위험이 특정 출퇴근 시간에만 집중되는 것이 아니라,
# 낮시간에도 환승·구조·유입 요인이 복합적으로 작용해
# 고위험 구간이 많이 나타난다는 것을 의미한다.
#
# 따라서 안전대책은 출퇴근 시간 중심의 일시적 대응뿐 아니라,
# 낮시간 주요 환승역과 구조위험역까지 포함하는 상시 관리 전략이 필요하다.

# What-if 정책 민감도 분석
## 가정 기반 시뮬레이션
- 목적: 특정 위험요인이 완화된다고 가정했을 때, Risk Score가 얼마나 낮아지는지 확인

In [ ]:
# What-if 정책 민감도 분석 함수
# 특정 위험요인이 일정 비율 완화된다고 가정했을 때
# Risk Score 변화량을 계산

def what_if_analysis(station, line, time_group, factor, reduction_rate=0.1):
    result = df[
        (df['역명_clean'] == station) &
        (df['호선명'] == line) &
        (df['time_group'] == time_group)
    ]

    if result.empty:
        print("해당 조건의 결과가 없습니다.")
        return

    row = result.iloc[0]

    factor_col_map = {
        '환승': '환승기여도',
        '구조': '구조기여도',
        '혼잡': '혼잡기여도',
        '유입': '유입기여도'
    }

    if factor not in factor_col_map:
        print("factor는 '환승', '구조', '혼잡', '유입' 중 하나로 입력하세요.")
        return

    current_score = row['Risk_Score']
    contribution = row[factor_col_map[factor]]

    # 가정 기반 계산:
    # 해당 요인 기여도만큼 Risk Score에 영향을 준다고 보고,
    # 그 요인을 reduction_rate만큼 완화했을 때의 점수 감소분 계산
    score_reduction = current_score * (contribution / 100) * reduction_rate
    new_score = current_score - score_reduction

    print("=" * 70)
    print("🚇 MetroGuard-AI What-if 정책 민감도 분석")
    print("=" * 70)
    print(f"분석 대상: {station} / {line} / {time_group}")
    print(f"현재 Risk Score: {current_score:.1f}점")
    print()
    print(f"완화 가정 요인: {factor} 요인")
    print(f"해당 요인 기여도: {contribution:.1f}%")
    print(f"완화 가정 비율: {reduction_rate * 100:.0f}%")
    print()
    print(f"예상 Risk Score 감소폭: {score_reduction:.1f}점")
    print(f"What-if 적용 후 Risk Score: {new_score:.1f}점")
    print()
    print("해석:")
    print("본 결과는 실제 정책 효과를 단정하는 것이 아니라,")
    print("특정 위험요인이 완화된다는 가정하에 Risk Score 변화 방향을 확인하는 민감도 분석입니다.")
    print("=" * 70)

In [ ]:
what_if_analysis('사당', '2호선', '퇴근시간', '환승', reduction_rate=0.1)

======================================================================
🚇 MetroGuard-AI What-if 정책 민감도 분석
======================================================================
분석 대상: 사당 / 2호선 / 퇴근시간
현재 Risk Score: 89.6점

완화 가정 요인: 환승 요인
해당 요인 기여도: 41.3%
완화 가정 비율: 10%

예상 Risk Score 감소폭: 3.7점
What-if 적용 후 Risk Score: 85.9점

해석:
본 결과는 실제 정책 효과를 단정하는 것이 아니라,
특정 위험요인이 완화된다는 가정하에 Risk Score 변화 방향을 확인하는 민감도 분석입니다.
======================================================================

In [ ]:
what_if_analysis('사당', '2호선', '퇴근시간', '환승', reduction_rate=0.2)

======================================================================
🚇 MetroGuard-AI What-if 정책 민감도 분석
======================================================================
분석 대상: 사당 / 2호선 / 퇴근시간
현재 Risk Score: 89.6점

완화 가정 요인: 환승 요인
해당 요인 기여도: 41.3%
완화 가정 비율: 20%

예상 Risk Score 감소폭: 7.4점
What-if 적용 후 Risk Score: 82.2점

해석:
본 결과는 실제 정책 효과를 단정하는 것이 아니라,
특정 위험요인이 완화된다는 가정하에 Risk Score 변화 방향을 확인하는 민감도 분석입니다.
======================================================================

In [ ]:
# 최종: 드롭다운 기반 What-if 정책 민감도 분석 시스템

import ipywidgets as widgets
from IPython.display import display, clear_output, Markdown

# 시스템 설명
display(Markdown("""
# 🧪 MetroGuard-AI What-if 정책 민감도 분석

이 시스템은 실제 정책 효과를 단정하지 않고,
특정 위험요인이 일정 비율 완화된다고 가정했을 때
**Risk Score가 얼마나 변하는지 확인하는 가정 기반 민감도 분석**입니다.

- **완화요인**: 정책을 통해 줄인다고 가정할 위험요인
  - 환승: 환승 동선 복잡도 완화
  - 구조: 승강장 구조·시설 위험 완화
  - 혼잡: 승하차 인원 및 승강장 밀집 완화
  - 유입: 역 주변 외부 유입 인구 집중 완화

- **완화비율**
  - 10% 완화: 낮은 강도 개선 시나리오
  - 20% 완화: 중간 강도 개선 시나리오
  - 30% 완화: 높은 강도 개선 시나리오

※ 실제 정책 효과가 아니라, 위험요인 변화에 따른 Risk Score 민감도를 보기 위한 분석입니다.
"""))

# 선택지 설정
station_options = sorted(df['역명_clean'].dropna().unique())

factor_options = [
    ('환승 요인 완화', '환승'),
    ('구조 요인 완화', '구조'),
    ('혼잡 요인 완화', '혼잡'),
    ('유입 요인 완화', '유입')
]

reduction_options = {
    '10% 완화 / 낮은 강도 개선': 0.1,
    '20% 완화 / 중간 강도 개선': 0.2,
    '30% 완화 / 높은 강도 개선': 0.3
}

# 드롭다운 UI
station_dropdown_w = widgets.Dropdown(
    options=station_options,
    description='역명:',
    layout=widgets.Layout(width='360px')
)

line_dropdown_w = widgets.Dropdown(
    options=[],
    description='호선:',
    layout=widgets.Layout(width='360px')
)

time_dropdown_w = widgets.Dropdown(
    options=[],
    description='시간대:',
    layout=widgets.Layout(width='360px')
)

factor_dropdown = widgets.Dropdown(
    options=factor_options,
    description='완화요인:',
    layout=widgets.Layout(width='360px')
)

reduction_dropdown = widgets.Dropdown(
    options=reduction_options,
    description='완화비율:',
    layout=widgets.Layout(width='360px')
)

button_w = widgets.Button(
    description='What-if 분석',
    button_style='warning',
    icon='flask',
    layout=widgets.Layout(width='200px')
)

output_w = widgets.Output()


# 역명 선택 시 해당 역의 호선만 표시
def update_line_options_w(*args):
    station = station_dropdown_w.value

    lines = sorted(
        df[df['역명_clean'] == station]['호선명']
        .dropna()
        .unique()
    )

    line_dropdown_w.options = lines

    if len(lines) > 0:
        line_dropdown_w.value = lines[0]

    update_time_options_w()


# 역명 + 호선 선택 시 해당 조건의 시간대만 표시
def update_time_options_w(*args):
    station = station_dropdown_w.value
    line = line_dropdown_w.value

    times = sorted(
        df[
            (df['역명_clean'] == station) &
            (df['호선명'] == line)
        ]['time_group']
        .dropna()
        .unique()
    )

    time_dropdown_w.options = times

    if len(times) > 0:
        time_dropdown_w.value = times[0]


# 버튼 클릭 시 What-if 분석 실행
def on_button_click_w(b):
    with output_w:
        clear_output()

        station = station_dropdown_w.value
        line = line_dropdown_w.value
        time_group = time_dropdown_w.value
        factor = factor_dropdown.value
        reduction_rate = reduction_dropdown.value

        what_if_analysis(
            station,
            line,
            time_group,
            factor,
            reduction_rate=reduction_rate
        )


# 이벤트 연결
station_dropdown_w.observe(update_line_options_w, names='value')
line_dropdown_w.observe(update_time_options_w, names='value')
button_w.on_click(on_button_click_w)

# 초기값 설정
update_line_options_w()

# UI 출력
display(
    station_dropdown_w,
    line_dropdown_w,
    time_dropdown_w,
    factor_dropdown,
    reduction_dropdown,
    button_w,
    output_w
)

# 🧪 MetroGuard-AI What-if 정책 민감도 분석

이 시스템은 실제 정책 효과를 단정하지 않고,
특정 위험요인이 일정 비율 완화된다고 가정했을 때
**Risk Score가 얼마나 변하는지 확인하는 가정 기반 민감도 분석**입니다.

- **완화요인**: 정책을 통해 줄인다고 가정할 위험요인
  - 환승: 환승 동선 복잡도 완화
  - 구조: 승강장 구조·시설 위험 완화
  - 혼잡: 승하차 인원 및 승강장 밀집 완화
  - 유입: 역 주변 외부 유입 인구 집중 완화

- **완화비율**
  - 10% 완화: 낮은 강도 개선 시나리오
  - 20% 완화: 중간 강도 개선 시나리오
  - 30% 완화: 높은 강도 개선 시나리오

※ 실제 정책 효과가 아니라, 위험요인 변화에 따른 Risk Score 민감도를 보기 위한 분석입니다.

Dropdown(description='역명:', layout=Layout(width='360px'), options=('가락시장', '가산디지털단지', '가양', '강남', '강남구청', '강동'…

Dropdown(description='호선:', layout=Layout(width='360px'), options=('3호선', '8호선'), value='3호선')

Dropdown(description='시간대:', layout=Layout(width='360px'), options=('기타', '낮시간', '출근시간', '퇴근시간'), value='기타')

Dropdown(description='완화요인:', layout=Layout(width='360px'), options=(('환승 요인 완화', '환승'), ('구조 요인 완화', '구조'), (…

Dropdown(description='완화비율:', layout=Layout(width='360px'), options={'10% 완화 / 낮은 강도 개선': 0.1, '20% 완화 / 중간 강도…

Button(button_style='warning', description='What-if 분석', icon='flask', layout=Layout(width='200px'), style=But…

Output()